### ISSUE TITLE
charm refresh from revision `134` to revision `164` puts all units in error state

### ISSUE THREAD

**Issue by nishant-dash** [canonical/tempo-coordinator-k8s-operator#108]
### Bug Description

I deployed grafana agent and related it to k8s charms. one of the units was stuck in `waiting` with the message 
```console
grafana-agent-k8s/9*  waiting   idle            a.b.c.d            Waiting for TLS certificate.
```

```console
lib/charms/certificate_transfer_interface/v0/certificate_transfer.py:                f"Provider relation data did not pass JSON Schema validation: "
lib/charms/tls_certificates_interface/v2/tls_certificates.py:            logger.warning("Provider relation data did not pass JSON Schema validation")
```

I tried to refresh the charm to the latest in `latest/stable` (which happens to be rev `164` right now)
putting all units in error state 

```console
grafana-agent-k8s                    error           11  grafana-agent               latest/stable  164  no       hook failed: "upgrade-charm"
  grafana-agent-k8s/10           error        idle                a.b.c.d                  hook failed: "upgrade-charm"
  grafana-agent-k8s/0            error        idle                a.b.c.d                  hook failed: "upgrade-charm"
  grafana-agent-k8s/1            error        idle                a.b.c.d                  hook failed: "upgrade-charm"
  grafana-agent-k8s/2            error        idle                a.b.c.d                  hook failed: "upgrade-charm"
  grafana-agent-k8s/9*           error        idle                a.b.c.d                  hook failed: "upgrade-charm"
  grafana-agent-k8s/3            error        idle                a.b.c.d                  hook failed: "upgrade-charm"
  grafana-agent-k8s/5            error        idle                a.b.c.d                  hook failed: "upgrade-charm"
  grafana-agent-k8s/4            error        idle                a.b.c.d                  hook failed: "upgrade-charm"
  grafana-agent-k8s/8            error        idle                a.b.c.d                  hook failed: "upgrade-charm"
  grafana-agent-k8s/7            error        idle                a.b.c.d                  hook failed: "upgrade-charm"
  grafana-agent-k8s/11           error        idle                a.b.c.d                  hook failed: "upgrade-charm"
cos-proxy-monitors:cos-agent                          grafana-agent-k8s:cos-agent                               cos_agent                      subordinate  
grafana-agent-k8s:grafana-dashboards-provider         grafana-dashboards:grafana-dashboard                      grafana_dashboard              regular      
grafana-agent-k8s:peers                               grafana-agent-k8s:peers                                   grafana_agent_replica          peer         
kubernetes-control-plane:cos-agent                    grafana-agent-k8s:cos-agent                               cos_agent                      subordinate  
kubernetes-worker:cos-agent                           grafana-agent-k8s:cos-agent                               cos_agent                      subordinate  
loki-logging:logging                                  grafana-agent-k8s:logging-consumer                        loki_push_api                  regular      
openstack-integrator:juju-info                        grafana-agent-k8s:juju-info                               juju-info                      subordinate  
prometheus-receive-remote-write:receive-remote-write  grafana-agent-k8s:send-remote-write                       prometheus_remote_write        regular      
vault:certificates                                    grafana-agent-k8s:certificates                            tls-certificates               regula
```

### To Reproduce

1. juju deploy grafana-agent --channel=latest/stable --revision=134
2. juju integrate grafana-agent ubuntu # or something
3. juju refresh grafana-agent # rev 164 as of opening this bug

### Environment

juju `3.4.3`
grafana-agent `latest/stable` revision `134`

### Relevant log output

```shell
unit-grafana-agent-k8s-9: 17:18:06 INFO juju.worker.uniter.charm downloading ch:amd64/jammy/grafana-agent-164 from API server
unit-grafana-agent-k8s-9: 17:18:06 ERROR juju.worker.uniter resolver loop error: preparing operation "upgrade to ch:amd64/jammy/grafana-agent-164" for grafana-agent-k8s/9: failed to download charm "ch:amd64/jammy/grafana-agent-164" from API server: download request with archiveSha256 length 0 not valid
unit-grafana-agent-k8s-9: 17:18:06 INFO juju.worker.uniter unit "grafana-agent-k8s/9" shutting down: preparing operation "upgrade to ch:amd64/jammy/grafana-agent-164" for grafana-agent-k8s/9: failed to download charm "ch:amd64/jammy/grafana-agent-164" from API server: download request with archiveSha256 length 0 not valid
unit-grafana-agent-k8s-9: 17:18:06 ERROR juju.worker.dependency "uniter" manifold worker returned unexpected error: preparing operation "upgrade to ch:amd64/jammy/grafana-agent-164" for grafana-agent-k8s/9: failed to download charm "ch:amd64/jammy/grafana-agent-164" from API server: download request with archiveSha256 length 0 not valid
unit-grafana-agent-k8s-9: 17:18:09 INFO juju.worker.uniter unit "grafana-agent-k8s/9" started
unit-grafana-agent-k8s-9: 17:18:09 INFO juju.worker.uniter hooks are retried true
unit-grafana-agent-k8s-9: 17:18:09 INFO juju.worker.uniter.charm downloading ch:amd64/jammy/grafana-agent-164 from API server
unit-grafana-agent-k8s-9: 17:18:36 INFO juju.worker.uniter found queued "upgrade-charm" hook
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm Failed to load context: contextvars_context, fallback to contextvars_context
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm Traceback (most recent call last):
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm   File "/var/lib/juju/agents/unit-grafana-agent-k8s-9/charm/venv/opentelemetry/context/__init__.py", line 45, in _load_runtime_context
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm     return next(  # type: ignore
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm StopIteration
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm Traceback (most recent call last):
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm   File "/var/lib/juju/agents/unit-grafana-agent-k8s-9/charm/venv/opentelemetry/context/__init__.py", line 45, in _load_runtime_context
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm     return next(  # type: ignore
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm StopIteration
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm 
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm During handling of the above exception, another exception occurred:
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm 
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm Traceback (most recent call last):
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm   File "/var/lib/juju/agents/unit-grafana-agent-k8s-9/charm/./src/charm.py", line 17, in <module>
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm     from charms.tempo_k8s.v1.charm_tracing import trace_charm
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm   File "/var/lib/juju/agents/unit-grafana-agent-k8s-9/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 125, in <module>
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm     from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm   File "/var/lib/juju/agents/unit-grafana-agent-k8s-9/charm/venv/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py", line 25, in <module>
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm     from opentelemetry.exporter.otlp.proto.common._internal import (
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm   File "/var/lib/juju/agents/unit-grafana-agent-k8s-9/charm/venv/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 45, in <module>
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm     from opentelemetry.sdk.trace import Resource
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm   File "/var/lib/juju/agents/unit-grafana-agent-k8s-9/charm/venv/opentelemetry/sdk/trace/__init__.py", line 44, in <module>
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm     from opentelemetry import context as context_api
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm   File "/var/lib/juju/agents/unit-grafana-agent-k8s-9/charm/venv/opentelemetry/context/__init__.py", line 69, in <module>
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm     _RUNTIME_CONTEXT = _load_runtime_context()
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm   File "/var/lib/juju/agents/unit-grafana-agent-k8s-9/charm/venv/opentelemetry/context/__init__.py", line 59, in _load_runtime_context
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm     return next(  # type: ignore
unit-grafana-agent-k8s-9: 17:18:36 WARNING unit.grafana-agent-k8s/9.upgrade-charm StopIteration
unit-grafana-agent-k8s-9: 17:18:37 ERROR juju.worker.uniter.operation hook "upgrade-charm" (via hook dispatching script: dispatch) failed: exit status 1
unit-grafana-agent-k8s-9: 17:18:37 INFO juju.worker.uniter awaiting error resolution for "upgrade-charm" hook
unit-grafana-agent-k8s-9: 17:18:42 INFO juju.worker.uniter awaiting error resolution for "upgrade-charm" hook
unit-grafana-agent-k8s-9: 17:18:42 WARNING unit.grafana-agent-k8s/9.upgrade-charm Failed to load context: contextvars_context, fallback to contextvars_context
```

### Additional context

Ignore the confusing charm name (not to be confused with the k8s grafana agent charm)

**Comment by PietroPasotti** [comment]
issue probably is that #57 Introduced a regression by importing otlp before the patch to remove stale otlp sdk packages. Testing now...

**Comment by alanbach** [comment]
@PietroPasotti Let me know once we have something for testing, I can test on my cloud

**Comment by alanbach** [comment]
Hello @PietroPasotti Thank you so much for looking into this!

I refreshed the charm:

```
$ juju refresh cos-agent --channel latest/edge
Added charm-hub charm "grafana-agent", revision 429 in channel latest/edge, to the model
no change to endpoints in space "alpha": certificates, cos-agent, grafana-cloud-config, grafana-dashboards-provider, juju-info, logging-consumer, peers, receive-ca-cert, send-remote-write, tracing
```
did a --no-retry on the upgrade-charm hook, but now the config change hook is in error with the same trace:

```
unit-cos-agent-0: 14:19:17 ERROR juju.worker.uniter.operation hook "config-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-cos-agent-0: 14:19:17 INFO juju.worker.uniter awaiting error resolution for "config-changed" hook
unit-cos-agent-0: 14:19:38 INFO juju.worker.uniter awaiting error resolution for "config-changed" hook
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed Failed to load context: contextvars_context, fallback to contextvars_context
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed Traceback (most recent call last):
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed   File "/var/lib/juju/agents/unit-cos-agent-0/charm/venv/opentelemetry/context/__init__.py", line 43, in _load_runtime_context
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed     return next(  # type: ignore
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed StopIteration
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed Traceback (most recent call last):
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed   File "/var/lib/juju/agents/unit-cos-agent-0/charm/venv/opentelemetry/context/__init__.py", line 43, in _load_runtime_context
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed     return next(  # type: ignore
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed StopIteration
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed 
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed During handling of the above exception, another exception occurred:
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed 
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed Traceback (most recent call last):
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed   File "/var/lib/juju/agents/unit-cos-agent-0/charm/./src/charm.py", line 19, in <module>
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed     from charms.tempo_coordinator_k8s.v0.charm_tracing import trace_charm
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed   File "/var/lib/juju/agents/unit-cos-agent-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 316, in <module>
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed     from opentelemetry.exporter.otlp.proto.common._internal.trace_encoder import (
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed   File "/var/lib/juju/agents/unit-cos-agent-0/charm/venv/opentelemetry/exporter/otlp/proto/common/_internal/__init__.py", line 46, in <module>
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed     from opentelemetry.sdk.trace import Resource
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed   File "/var/lib/juju/agents/unit-cos-agent-0/charm/venv/opentelemetry/sdk/trace/__init__.py", line 45, in <module>
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed     from opentelemetry import context as context_api
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed   File "/var/lib/juju/agents/unit-cos-agent-0/charm/venv/opentelemetry/context/__init__.py", line 67, in <module>
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed     _RUNTIME_CONTEXT = _load_runtime_context()
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed   File "/var/lib/juju/agents/unit-cos-agent-0/charm/venv/opentelemetry/context/__init__.py", line 57, in _load_runtime_context
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed     return next(  # type: ignore
unit-cos-agent-0: 14:19:38 WARNING unit.cos-agent/0.config-changed StopIteration
unit-cos-agent-0: 14:19:38 ERROR juju.worker.uniter.operation hook "config-changed" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by PietroPasotti** [comment]
the upgrade hook should be allowed to run; that's what triggers the patch that is supposed to solve this issue.
If this isn't production: what happens if you do `jhack fire cos-agent/0 upgrade-charm`?

**Comment by alanbach** [comment]
Never mind my last question - I just realized it also has an application mode

**Comment by PietroPasotti** [comment]
@alanbach is this solved then?

**Comment by mmkay** [comment]
The underlying issue that we wrote a workaround for should be fixed in Juju 3.5.4+: https://bugs.launchpad.net/juju/+bug/2058335

@alanbach would it be possible for you to re-validate it on a newer Juju version? 

We should also add this case to grafana-agent's documentation, possibly here: https://discourse.charmhub.io/t/grafana-agent-docs-troubleshooting-integrations/14935 so that people that encounter this issue know what to do.

**Comment by alanbach** [comment]
Hey @PietroPasotti So far so good! The application mode for jhack gets stuck for some reason, so I'm just going unit by unit in a for loop.

Hey @mmkay I have two sets of Juju controllers, 3.3.5 and 3.6.2. This issue only appeared on 3.3.5 models - none of the models on the 3.6.2 controllers experienced this. So this confirms the fix in 3.5.4+

**Comment by alanbach** [comment]
One more data point, on remaining models on Juju controller 3.3.5 going from revision 223 directly to 429 works without failing.

**Comment by henryoudaimy** [comment]
Hey @PietroPasotti , if we upgrade Juju to a version higher than 3.5.4, could this fix the issue? (grafana-agent deployed using the latest/stable channel)

**Comment by alanbach** [comment]
Hello @PietroPasotti @mmkay One more question: Do you think if we upgrade the underlying juju controller in an affected environment to 3.5.4 that will potentially avoid using the jhack tool? 

I'm also thinking migrating the models containing these units in error state might also be another problem and a non-starter.

I would really appreciate if you can share your thoughts?

**Comment by PietroPasotti** [comment]
hey sorry for the late response, somehow I didn't get notifications for them. Please reach us in https://app.element.io/?updated=1.11.92#/room/#cos:ubuntu.com for a more direct communication line.

I think upgrading the controller (before doing the charm upgrade/refresh) could fix the issue, however I'm not sure if upgrading the controller will also upgrade the unit-agents. Asking juju folks...

**Comment by PietroPasotti** [comment]
> Hey [@PietroPasotti](https://github.com/PietroPasotti) So far so good! The application mode for jhack gets stuck for some reason, so I'm just going unit by unit in a for loop.

If you want to open an issue on github.com/canonical/jhack I'll take a look!

> Hey [@mmkay](https://github.com/mmkay) I have two sets of Juju controllers, 3.3.5 and 3.6.2. This issue only appeared on 3.3.5 models - none of the models on the 3.6.2 controllers experienced this. So this confirms the fix in 3.5.4+

Good to hear!

**Comment by PietroPasotti** [comment]
see discussion on https://bugs.launchpad.net/juju/+bug/2058335 for more context.
I wrote up a doc on troubleshooting this issue. WDYT @alanbach @henryoudaimy @mmkay?

**Comment by alanbach** [comment]
Hello @PietroPasotti The document looks good! Thank you so much for this. I'm going to bookmark it in case someone else hits this.

Regarding the jhack I think the issue was I needed to run juju resolve a couple of times before it kicked in. I believe that was causing the jhack to get stuck.

**Comment by mmkay** [comment]
@alanbach thank you for the feedback! We'll be closing the issue for now. In case you get any further issues, please feel free to reach out to us.
