### ISSUE TITLE
[charm_tracing] clean up charm stack traces

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/tempo-coordinator-k8s-operator#74]
### Enhancement Proposal

As a charmer, I wish that exceptions raised in charm code bubbled up through charm-tracing-decorated methods without cluttering the stack trace with charm_tracing internals.

ATM the stack trace leaks `charm_tracing` internal decorator frames such as `_wrap_function`

```
unit-mysql-k8s-2: 22:11:21 ERROR juju.worker.uniter pebble poll failed for container "mysql": failed to send pebble-ready event: terminated
unit-mysql-k8s-2: 22:11:22 ERROR unit.mysql-k8s/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/./src/charm.py", line 929, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/./src/charm.py", line 700, in _on_mysql_pebble_ready
    self._reconcile_pebble_layer(container)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/./src/charm.py", line 412, in _reconcile_pebble_layer
    container.replan()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/model.py", line 2259, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/pebble.py", line 2129, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/pebble.py", line 2226, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mysqld_safe" (cannot start service while terminating)
----- Logs from task 0 -----
2024-09-17T22:11:22Z ERROR cannot start service while terminating
```

**Comment by dimaqq** [comment]
My 2c:

if the exception is expected, it should be caught and something logical returned or re-raised. Traceback is then a moot point.

if the exception is not expected, I would rather have the full traceback.

I suppose I would take own preference with a grain of salt though, for example Java stack traces are quite hard to grok as they are often 300+ lines. Would you provide an actual trace back to discuss?

**Comment by PietroPasotti** [comment]
updated with an example

**Comment by PietroPasotti** [comment]
and yes, it's about uncaught charm exceptions

**Comment by dimaqq** [comment]
How about this as a straw-man counter-proposal:

ops would catch all `Exception`'s at `custom_handler(event)`, log the lower half of the traceback and exit (appropriate exit code, but otherwise "cleanly")?

**Comment by tonyandrewmeyer** [comment]
I think the issue here is less that the tracing wrappers are in the traceback, and more that they are mixed in, right? e.g. if the traceback was something like this:

```
unit-mysql-k8s-2: 22:11:21 ERROR juju.worker.uniter pebble poll failed for container "mysql": failed to send pebble-ready event: terminated
unit-mysql-k8s-2: 22:11:22 ERROR unit.mysql-k8s/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/./src/charm.py", line 929, in <module>
    main(MySQLOperatorCharm)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 551, in main
    manager.run()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 530, in run
    self._emit()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 519, in _emit
    _emit_charm_event(self.charm, self.dispatcher.event_name)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/main.py", line 147, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 348, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 860, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/framework.py", line 950, in _reemit
    custom_handler(event)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/charm_tracing.py", line 735, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/./src/charm.py", line 700, in _on_mysql_pebble_ready
    self._reconcile_pebble_layer(container)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/./src/charm.py", line 412, in _reconcile_pebble_layer
    container.replan()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/model.py", line 2259, in replan
    self._pebble.replan_services()
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/pebble.py", line 2129, in replan_services
    return self._services_action('replan', [], timeout, delay)
  File "/var/lib/juju/agents/unit-mysql-k8s-2/charm/venv/ops/pebble.py", line 2226, in _services_action
    raise ChangeError(change.err, change)
ops.pebble.ChangeError: cannot perform the following tasks:
- Start service "mysqld_safe" (cannot start service while terminating)
----- Logs from task 0 -----
2024-09-17T22:11:22Z ERROR cannot start service while terminating
```

Then this seems no worse than a normal traceback to deal with - you work your way up until you leave the code that you wrote and ignore everything above it (all the framework machinery). Where it's inconvenient now is (a) the tracing code is in a lib so it's harder to determine whether it's your issue or not - which gets solved by ops providing his, and (b) there's a `wrapped_function` after your charm code.

Would it be possible to get enough information for generic tracing using sys.settrace or sys.setprofile or sys.monitoring (ignoring the minimum Python requirement problem)? Avoiding the decorating seems like it would avoid the issue.

**Comment by mmkay** [comment]
There doesn't seem to be a clean way to solve the problem. An idea:

- maybe charm_tracing should catch the exception, check if we aren't at the top of the call stack and re-raise it with "this is likely not a charm tracing issue" in a similar way that pip does it?
